"""G-code parser for FDM 3D-printer files.

Single-pass, state-preserving parser that tracks modal G-code state
(G90/G91 for XYZ, M82/M83 for E, current feedrate) and computes:
- axis bounds (min/max for X, Y, Z) and print size
- travel vs. extrusion distance
- total filament length consumed (sum of positive dE)
- estimated print time (sum of dist / feedrate, no acceleration model)
- layer count (preferred: slicer ;LAYER:/;LAYER_COUNT: comments;
  fallback: unique Z values at which extrusion occurred)
"""

from __future__ import annotations

import math
import re
from typing import Iterable

_TOKEN_RE = re.compile(r"([XYZEFIJRxyzefijr])(-?\d+(?:\.\d+)?)")
_LAYER_COUNT_RE = re.compile(r";\s*LAYER_COUNT\s*:\s*(\d+)", re.IGNORECASE)
_LAYER_RE = re.compile(r";\s*LAYER\s*:\s*(-?\d+)", re.IGNORECASE)

# --- Slicer header detection (Cura, PrusaSlicer/SuperSlicer, OrcaSlicer) ---
# Time
_CURA_TIME_RE = re.compile(r";\s*TIME\s*:\s*(\d+)", re.IGNORECASE)
_PRUSA_TIME_RE = re.compile(
    r";\s*estimated printing time(?:\s*\([^)]*\))?\s*=\s*(.+?)\s*$",
    re.IGNORECASE,
)
# Filament length
_CURA_FIL_LEN_M_RE = re.compile(
    r";\s*Filament used\s*:\s*([\d.]+)\s*m\b", re.IGNORECASE
)
_PRUSA_FIL_LEN_MM_RE = re.compile(
    r";\s*filament used\s*\[mm\]\s*=\s*([\d.]+)", re.IGNORECASE
)
# Filament mass
_PRUSA_FIL_G_RE = re.compile(
    r";\s*(?:filament used \[g\]|total filament used \[g\]|filament weight)"
    r"\s*=\s*([\d.]+)",
    re.IGNORECASE,
)
# Layer height
_CURA_LH_RE = re.compile(r";\s*LAYER_HEIGHT\s*:\s*([\d.]+)", re.IGNORECASE)
_PRUSA_LH_RE = re.compile(r";\s*layer_height\s*=\s*([\d.]+)", re.IGNORECASE)
# Slicer name
_GENERATED_BY_RE = re.compile(
    r";\s*(?:generated by|generated with)\s+(.+?)\s*$", re.IGNORECASE
)
_CURA_BANNER_RE = re.compile(r"(Cura_SteamEngine[\w.\-]*)", re.IGNORECASE)


def _parse_prusa_time(text: str) -> float | None:
    """Parse PrusaSlicer time string like '1h 23m 4s' or '23m 4s' into seconds."""
    total = 0.0
    matched = False
    for amount, unit in re.findall(
        r"(\d+(?:\.\d+)?)\s*([dhms])", text, flags=re.IGNORECASE
    ):
        matched = True
        v = float(amount)
        u = unit.lower()
        if u == "d":
            total += v * 86400
        elif u == "h":
            total += v * 3600
        elif u == "m":
            total += v * 60
        else:
            total += v
    return total if matched else None

# Default filament assumptions for mass estimation.
# 1.75 mm filament + PLA (~1.24 g/cm^3) is the most common FDM combo.
DEFAULT_FILAMENT_DIAMETER_MM = 1.75
DEFAULT_FILAMENT_DENSITY_G_CM3 = 1.24

# Default printer acceleration (mm/s^2). Typical Marlin firmware default is
# ~1500 mm/s^2 for printing moves; many printers run higher (3000+) for
# travel. We use a single conservative value as a rough approximation.
DEFAULT_ACCEL_MM_S2 = 1500.0


def _trapezoid_time(dist: float, v_target: float, accel: float | None) -> float:
    """Time to travel `dist` mm assuming start/end at rest.

    With acceleration model (`accel` > 0): trapezoidal velocity profile
    (accelerate to v_target, cruise, decelerate). If the segment is too
    short to reach v_target, the profile becomes triangular.

    Without acceleration model (`accel` is None or <= 0): the naive
    `dist / v_target` (instant velocity changes) is used.
    """
    if dist <= 0 or v_target <= 0:
        return 0.0
    if accel is None or accel <= 0:
        return dist / v_target
    # Distance needed to reach v_target from rest under constant accel:
    # d_accel = v^2 / (2a)
    d_accel = (v_target * v_target) / (2.0 * accel)
    if dist >= 2.0 * d_accel:
        # Trapezoid: accel + cruise + decel.
        t_accel = v_target / accel
        cruise_dist = dist - 2.0 * d_accel
        return 2.0 * t_accel + cruise_dist / v_target
    # Triangle: never reaches v_target. Peak velocity v_peak = sqrt(a * dist).
    # Total time = 2 * v_peak / a = 2 * sqrt(dist / a).
    return 2.0 * math.sqrt(dist / accel)


def _typical_layer_height(zs: list[float]) -> float | None:
    """Median of consecutive differences (robust to first-layer offsets)."""
    if len(zs) < 2:
        return None
    diffs = [round(b - a, 4) for a, b in zip(zs, zs[1:]) if b - a > 1e-4]
    if not diffs:
        return None
    diffs.sort()
    return diffs[len(diffs) // 2]


DEFAULT_TOOLPATH_MAX_SEGMENTS = 80_000


def analyze(
    lines: Iterable[str],
    filament_diameter_mm: float = DEFAULT_FILAMENT_DIAMETER_MM,
    filament_density_g_cm3: float = DEFAULT_FILAMENT_DENSITY_G_CM3,
    accel_mm_s2: float | None = DEFAULT_ACCEL_MM_S2,
    collect_toolpath: bool = False,
    toolpath_max_segments: int = DEFAULT_TOOLPATH_MAX_SEGMENTS,
) -> dict:
    # Modal state.
    x = y = z = e = 0.0
    e_high_water = 0.0  # max E seen since last G92 E... (for absolute-mode filament accounting)
    feed = 0.0  # mm/min
    abs_xyz = True
    abs_e = True
    last_cmd: str | None = None  # for modal G0/G1 (rarely used without explicit code)

    inf = float("inf")
    # Motion bounds: any XYZ move (homing, probing, prime line, wipe, ...).
    min_x = min_y = min_z = inf
    max_x = max_y = max_z = -inf
    # Print bounds: only moves with active extrusion - represent the model envelope.
    min_px = min_py = min_pz = inf
    max_px = max_py = max_pz = -inf

    travel_dist = 0.0
    print_dist = 0.0
    filament_mm = 0.0
    time_s = 0.0
    print_time_s = 0.0
    travel_time_s = 0.0

    extrusion_zs: set[float] = set()
    slicer_layer_count: int | None = None
    slicer_layer_indices: set[int] = set()

    slicer_meta: dict[str, object | None] = {
        "name": None,
        "timeS": None,
        "filamentMm": None,
        "filamentG": None,
        "layerHeightMm": None,
    }

    line_count = 0
    has_any_move = False

    # Toolpath collection (optional). We collect ALL motion segments first
    # and decimate to <= toolpath_max_segments at the end. Each segment is
    # stored as (x1, y1, z1, x2, y2, z2, is_extrusion).
    toolpath_segments: list[tuple[float, float, float, float, float, float, bool]] = []

    for raw in lines:
        line_count += 1

        # Fast-path slicer comments before stripping them.
        if ";" in raw:
            m = _LAYER_COUNT_RE.search(raw)
            if m:
                try:
                    slicer_layer_count = int(m.group(1))
                except ValueError:
                    pass
            m = _LAYER_RE.search(raw)
            if m:
                try:
                    slicer_layer_indices.add(int(m.group(1)))
                except ValueError:
                    pass
            # Slicer metadata: only set if not already populated (first wins).
            if slicer_meta["name"] is None:
                m = _GENERATED_BY_RE.search(raw)
                if m:
                    slicer_meta["name"] = m.group(1).strip()
                else:
                    m = _CURA_BANNER_RE.search(raw)
                    if m:
                        slicer_meta["name"] = m.group(1).strip()
            if slicer_meta["timeS"] is None:
                m = _CURA_TIME_RE.search(raw)
                if m:
                    try:
                        slicer_meta["timeS"] = float(m.group(1))
                    except ValueError:
                        pass
                else:
                    m = _PRUSA_TIME_RE.search(raw)
                    if m:
                        parsed = _parse_prusa_time(m.group(1))
                        if parsed is not None:
                            slicer_meta["timeS"] = parsed
            if slicer_meta["filamentMm"] is None:
                m = _CURA_FIL_LEN_M_RE.search(raw)
                if m:
                    try:
                        slicer_meta["filamentMm"] = float(m.group(1)) * 1000.0
                    except ValueError:
                        pass
                else:
                    m = _PRUSA_FIL_LEN_MM_RE.search(raw)
                    if m:
                        try:
                            slicer_meta["filamentMm"] = float(m.group(1))
                        except ValueError:
                            pass
            if slicer_meta["filamentG"] is None:
                m = _PRUSA_FIL_G_RE.search(raw)
                if m:
                    try:
                        slicer_meta["filamentG"] = float(m.group(1))
                    except ValueError:
                        pass
            if slicer_meta["layerHeightMm"] is None:
                m = _CURA_LH_RE.search(raw)
                if m:
                    try:
                        slicer_meta["layerHeightMm"] = float(m.group(1))
                    except ValueError:
                        pass
                else:
                    m = _PRUSA_LH_RE.search(raw)
                    if m:
                        try:
                            slicer_meta["layerHeightMm"] = float(m.group(1))
                        except ValueError:
                            pass

        # Strip comment and whitespace.
        code = raw.split(";", 1)[0].strip()
        if not code:
            continue

        # Identify command word (first token, e.g. G1 / G0 / G28 / M82).
        head, _, _rest = code.partition(" ")
        head_up = head.upper()

        if head_up in ("G90",):
            abs_xyz = True
            abs_e = True
            continue
        if head_up in ("G91",):
            abs_xyz = False
            abs_e = False
            continue
        if head_up == "M82":
            abs_e = True
            continue
        if head_up == "M83":
            abs_e = False
            continue
        if head_up == "G92":
            # Reset coordinate system: G92 X.. Y.. Z.. E..
            for axis, val_s in _TOKEN_RE.findall(code):
                val = float(val_s)
                a = axis.upper()
                if a == "X":
                    x = val
                elif a == "Y":
                    y = val
                elif a == "Z":
                    z = val
                elif a == "E":
                    e = val
                    e_high_water = val
            continue

        if head_up in ("G0", "G1", "G00", "G01"):
            cmd = "G1"
        elif head_up in ("G2", "G02"):
            cmd = "G2"
        elif head_up in ("G3", "G03"):
            cmd = "G3"
        else:
            # Unknown / non-move command - ignore.
            last_cmd = head_up
            continue
        last_cmd = cmd

        new_x, new_y, new_z, new_e = x, y, z, e
        had_xyz = False
        had_e = False
        arc_i: float | None = None
        arc_j: float | None = None
        arc_r: float | None = None
        for axis, val_s in _TOKEN_RE.findall(code):
            val = float(val_s)
            a = axis.upper()
            if a == "X":
                new_x = val if abs_xyz else x + val
                had_xyz = True
            elif a == "Y":
                new_y = val if abs_xyz else y + val
                had_xyz = True
            elif a == "Z":
                new_z = val if abs_xyz else z + val
                had_xyz = True
            elif a == "E":
                new_e = val if abs_e else e + val
                had_e = True
            elif a == "F":
                if val > 0:
                    feed = val
            elif a == "I":
                arc_i = val
            elif a == "J":
                arc_j = val
            elif a == "R":
                arc_r = val

        if not (had_xyz or had_e):
            continue

        dx = new_x - x
        dy = new_y - y
        dz = new_z - z

        if cmd in ("G2", "G3") and (arc_i is not None or arc_j is not None):
            # Arc move with I/J center offsets (most common in slicers).
            cx = x + (arc_i or 0.0)
            cy = y + (arc_j or 0.0)
            r = math.hypot(x - cx, y - cy)
            theta_start = math.atan2(y - cy, x - cx)
            theta_end = math.atan2(new_y - cy, new_x - cx)
            sweep = theta_end - theta_start
            if cmd == "G2":  # clockwise: sweep must be <= 0
                if sweep > 0:
                    sweep -= 2 * math.pi
                if sweep == 0 and (
                    abs(dx) < 1e-9 and abs(dy) < 1e-9
                ):
                    sweep = -2 * math.pi  # full circle
            else:  # G3 ccw
                if sweep < 0:
                    sweep += 2 * math.pi
                if sweep == 0 and (
                    abs(dx) < 1e-9 and abs(dy) < 1e-9
                ):
                    sweep = 2 * math.pi
            arc_len = abs(sweep) * r
            dist = math.hypot(arc_len, dz)
        elif cmd in ("G2", "G3") and arc_r is not None:
            # R-form fallback: approximate as straight chord. Computing the
            # exact arc from R alone is ambiguous (two possible centers); the
            # error vs. straight chord is small for typical short arcs.
            dist = math.sqrt(dx * dx + dy * dy + dz * dz)
        else:
            dist = math.sqrt(dx * dx + dy * dy + dz * dz)
        de = new_e - e

        if had_xyz:
            has_any_move = True
            if new_x < min_x:
                min_x = new_x
            if new_x > max_x:
                max_x = new_x
            if new_y < min_y:
                min_y = new_y
            if new_y > max_y:
                max_y = new_y
            if new_z < min_z:
                min_z = new_z
            if new_z > max_z:
                max_z = new_z

        # Filament: only count NEW extrusion (E rising above the high-water mark
        # since the last G92 E... reset). This correctly ignores retract+unretract
        # cycles in absolute extrusion mode (M82) and matches sum-of-positive-dE
        # behavior in relative mode (M83).
        is_extrusion_move = False
        if new_e > e_high_water:
            filament_mm += new_e - e_high_water
            e_high_water = new_e
            is_extrusion_move = True

        if is_extrusion_move:
            if dist > 0:
                print_dist += dist
            # Track Z where extrusion happens (rounded to 3 decimals).
            extrusion_zs.add(round(new_z, 3))
            # Update print bounds with the segment endpoint (start is the previous
            # extrusion endpoint, which was added when we got to it).
            if had_xyz:
                if new_x < min_px:
                    min_px = new_x
                if new_x > max_px:
                    max_px = new_x
                if new_y < min_py:
                    min_py = new_y
                if new_y > max_py:
                    max_py = new_y
                if new_z < min_pz:
                    min_pz = new_z
                if new_z > max_pz:
                    max_pz = new_z
            # Also seed bounds with the starting point of this first extrusion
            # segment, otherwise a single G1 X.. E.. would only record the
            # endpoint. Cheap to do unconditionally - min/max idempotent.
            if x < min_px:
                min_px = x
            if x > max_px:
                max_px = x
            if y < min_py:
                min_py = y
            if y > max_py:
                max_py = y
            if z < min_pz:
                min_pz = z
            if z > max_pz:
                max_pz = z
        elif dist > 0:
            travel_dist += dist

        if dist > 0 and feed > 0:
            v_target = feed / 60.0  # mm/s
            seg_time = _trapezoid_time(dist, v_target, accel_mm_s2)
            time_s += seg_time
            if is_extrusion_move:
                print_time_s += seg_time
            else:
                travel_time_s += seg_time

        if collect_toolpath and had_xyz and dist > 0:
            toolpath_segments.append(
                (x, y, z, new_x, new_y, new_z, is_extrusion_move)
            )

        x, y, z, e = new_x, new_y, new_z, new_e

    # Layer count: prefer slicer hints, fallback to unique extrusion Z.
    if slicer_layer_count is not None:
        layer_count = slicer_layer_count
    elif slicer_layer_indices:
        layer_count = len(slicer_layer_indices)
    else:
        layer_count = len(extrusion_zs)

    sorted_zs = sorted(extrusion_zs)
    layer_height = _typical_layer_height(sorted_zs)

    has_extrusion = min_px != inf
    if has_extrusion:
        bounds = {
            "x": [min_px, max_px],
            "y": [min_py, max_py],
            "z": [min_pz, max_pz],
        }
        size = {
            "x": max_px - min_px,
            "y": max_py - min_py,
            "z": max_pz - min_pz,
        }
    elif has_any_move:
        # No extrusion at all (e.g. probing-only file): fall back to motion bounds.
        bounds = {
            "x": [min_x, max_x],
            "y": [min_y, max_y],
            "z": [min_z, max_z],
        }
        size = {
            "x": max_x - min_x,
            "y": max_y - min_y,
            "z": max_z - min_z,
        }
    else:
        bounds = {"x": [0.0, 0.0], "y": [0.0, 0.0], "z": [0.0, 0.0]}
        size = {"x": 0.0, "y": 0.0, "z": 0.0}

    if has_any_move:
        motion_bounds = {
            "x": [min_x, max_x],
            "y": [min_y, max_y],
            "z": [min_z, max_z],
        }
    else:
        motion_bounds = {"x": [0.0, 0.0], "y": [0.0, 0.0], "z": [0.0, 0.0]}

    total_dist = travel_dist + print_dist

    # Mass = length_mm * cross_section_mm^2 * density_g/cm^3 / 1000
    # (1 mm^3 = 0.001 cm^3)
    cross_section_mm2 = math.pi * (filament_diameter_mm / 2.0) ** 2
    filament_volume_mm3 = filament_mm * cross_section_mm2
    filament_g = filament_volume_mm3 * filament_density_g_cm3 / 1000.0

    result: dict = {
        "lineCount": line_count,
        "bounds": bounds,
        "size": size,
        "motionBounds": motion_bounds,
        "travelDistanceMm": travel_dist,
        "printDistanceMm": print_dist,
        "totalDistanceMm": total_dist,
        "filamentMm": filament_mm,
        "filamentM": filament_mm / 1000.0,
        "filamentG": filament_g,
        "filamentVolumeCm3": filament_volume_mm3 / 1000.0,
        "filamentDiameterMm": filament_diameter_mm,
        "filamentDensityGCm3": filament_density_g_cm3,
        "estimatedTimeS": time_s,
        "printTimeS": print_time_s,
        "travelTimeS": travel_time_s,
        "avgPrintSpeedMmS": (
            print_dist / print_time_s if print_time_s > 0 else None
        ),
        "avgTravelSpeedMmS": (
            travel_dist / travel_time_s if travel_time_s > 0 else None
        ),
        "layerCount": layer_count,
        "layerHeightMm": layer_height,
        "slicer": slicer_meta,
    }

    if collect_toolpath:
        total_segments = len(toolpath_segments)
        if total_segments > toolpath_max_segments and toolpath_max_segments > 0:
            step = math.ceil(total_segments / toolpath_max_segments)
            sampled = toolpath_segments[::step]
        else:
            step = 1
            sampled = toolpath_segments
        # Split into two flat coordinate arrays for fast Three.js consumption.
        # Each segment contributes 6 floats: x1,y1,z1,x2,y2,z2.
        ext_coords: list[float] = []
        trav_coords: list[float] = []
        for x1, y1, z1, x2, y2, z2, is_ext in sampled:
            target = ext_coords if is_ext else trav_coords
            target.extend((x1, y1, z1, x2, y2, z2))
        result["toolpath"] = {
            "extrusion": ext_coords,
            "travel": trav_coords,
            "totalSegments": total_segments,
            "sampledSegments": len(sampled),
            "decimationStep": step,
        }

    return result
