"""Unit tests for the G-code parser.

Each test feeds a small in-memory G-code string and asserts on specific
fields of the analyze() result. The intent is to lock down the current
behaviour before further changes (slicer headers, arcs, acceleration).
"""

from __future__ import annotations

import math

import pytest

from parser import analyze


def _run(src: str, **kwargs) -> dict:
    # Default to the naive (no-acceleration) time model for stable, exact
    # arithmetic in the existing time/speed tests. Tests that exercise the
    # acceleration model pass accel_mm_s2 explicitly.
    kwargs.setdefault("accel_mm_s2", None)
    return analyze(src.splitlines(), **kwargs)


def test_basic_xyz_bounds():
    src = """
    G90
    M82
    G1 X0 Y0 Z0.2 E0
    G1 X10 Y0 E1
    G1 X10 Y10 E2
    G1 X0 Y10 E3
    G1 X0 Y0 E4
    """
    r = _run(src)
    assert r["bounds"] == {"x": [0.0, 10.0], "y": [0.0, 10.0], "z": [0.2, 0.2]}
    assert r["size"] == {"x": 10.0, "y": 10.0, "z": 0.0}
    assert r["lineCount"] == len(src.splitlines())


def test_relative_xyz_g91():
    # G91: every X10 adds 10 to current x.
    src = """
    G91
    M82
    G1 X10 Y0 Z0.2 E1
    G1 X10 Y0 E2
    G1 X10 Y0 E3
    """
    r = _run(src)
    # First extrusion segment seeds bounds with the start point (0,0,0),
    # so x range is [0, 30] after three +10 hops.
    assert r["bounds"]["x"] == [0.0, 30.0]


def test_extrusion_m82_absolute():
    src = """
    G90
    M82
    G1 X0 Y0 Z0.2 E0
    G1 X10 Y0 E5
    G1 X20 Y0 E10
    """
    r = _run(src)
    assert r["filamentMm"] == pytest.approx(10.0)


def test_extrusion_m83_relative():
    src = """
    G90
    M83
    G1 X0 Y0 Z0.2
    G1 X10 Y0 E1
    G1 X20 Y0 E1
    G1 X30 Y0 E1
    """
    r = _run(src)
    assert r["filamentMm"] == pytest.approx(3.0)


def test_retract_unretract_m82_does_not_inflate_filament():
    """The high-water-mark accounting must ignore retract+unretract cycles."""
    src = """
    G90
    M82
    G1 X0 Y0 Z0.2 E0
    G1 X10 Y0 E1.0
    G1 E0.7
    G1 X20 Y0
    G1 E1.0
    G1 X30 Y0 E2.0
    """
    r = _run(src)
    assert r["filamentMm"] == pytest.approx(2.0)


def test_g92_e0_resets_high_water():
    src = """
    G90
    M82
    G1 X0 Y0 Z0.2 E0
    G1 X10 Y0 E5
    G92 E0
    G1 X20 Y0 E5
    G92 E0
    G1 X30 Y0 E5
    """
    r = _run(src)
    assert r["filamentMm"] == pytest.approx(15.0)


def test_layer_count_from_slicer_comments():
    src = """
    ;LAYER_COUNT:42
    G90
    M82
    G1 X0 Y0 Z0.2 E1
    G1 X10 Y0 E2
    """
    r = _run(src)
    assert r["layerCount"] == 42


def test_layer_count_fallback_unique_extrusion_z():
    src = """
    G90
    M82
    G1 X0 Y0 Z0.2 E1
    G1 X10 Y0 Z0.4 E2
    G1 X20 Y0 Z0.6 E3
    """
    r = _run(src)
    assert r["layerCount"] == 3


def test_print_bounds_excludes_homing():
    """Homing/probing moves to negative coordinates must NOT pollute bounds."""
    src = """
    G90
    M82
    G28
    G1 X-100 Y-100 Z5
    G1 X-100 Y0
    G1 X0 Y0 Z0.2 E0
    G1 X10 Y0 E1
    G1 X10 Y10 E2
    G1 X0 Y10 E3
    G1 X0 Y0 E4
    """
    r = _run(src)
    assert r["bounds"]["x"] == [0.0, 10.0]
    assert r["bounds"]["y"] == [0.0, 10.0]
    assert r["motionBounds"]["x"][0] == -100.0
    assert r["motionBounds"]["y"][0] == -100.0


def test_no_extrusion_falls_back_to_motion_bounds():
    src = """
    G90
    G28
    G1 X10 Y20 Z5
    """
    r = _run(src)
    # No extrusion: bounds == motionBounds.
    assert r["bounds"] == r["motionBounds"]
    assert r["bounds"]["x"] == [10.0, 10.0]


def test_g92_xyz_does_not_count_as_move():
    src = """
    G90
    M82
    G92 X100 Y100 Z0
    G1 X110 Y100 Z0.2 E1
    """
    r = _run(src)
    # After G92 X100 Y100, an X110 move should put bounds at [100, 110].
    assert r["bounds"]["x"] == [100.0, 110.0]


def test_parses_cura_slicer_comments():
    src = """
;FLAVOR:Marlin
;TIME:6180
;Filament used: 13.3033m
;Layer height: 0.2
;LAYER_COUNT:239
;LAYER_HEIGHT:0.2
;Generated with Cura_SteamEngine 5.6.0
G90
M82
G1 X0 Y0 Z0.2 E0
G1 X10 Y0 E1
"""
    r = _run(src)
    s = r["slicer"]
    assert s["name"] is not None and "Cura_SteamEngine" in s["name"]
    assert s["timeS"] == pytest.approx(6180.0)
    assert s["filamentMm"] == pytest.approx(13303.3)
    assert s["layerHeightMm"] == pytest.approx(0.2)


def test_parses_prusaslicer_comments():
    src = """
; generated by PrusaSlicer 2.7.4 on 2024-05-01
; estimated printing time (normal mode) = 1h 23m 4s
; filament used [mm] = 4357.21
; filament used [g] = 12.99
; layer_height = 0.2
G90
M83
G1 X0 Y0 Z0.2
G1 X10 Y0 E1
"""
    r = _run(src)
    s = r["slicer"]
    assert s["name"] is not None and "PrusaSlicer" in s["name"]
    assert s["timeS"] == pytest.approx(1 * 3600 + 23 * 60 + 4)
    assert s["filamentMm"] == pytest.approx(4357.21)
    assert s["filamentG"] == pytest.approx(12.99)
    assert s["layerHeightMm"] == pytest.approx(0.2)


def test_slicer_meta_absent_when_no_comments():
    src = """
G90
M82
G1 X0 Y0 Z0.2 E0
G1 X10 Y0 E1
"""
    r = _run(src)
    assert r["slicer"] == {
        "name": None,
        "timeS": None,
        "filamentMm": None,
        "filamentG": None,
        "layerHeightMm": None,
    }


def test_estimated_time_with_feedrate():
    # 100 mm at 6000 mm/min = 100 mm/s -> 1 second.
    src = """
    G90
    M82
    G1 F6000
    G1 X100 Y0 E1
    """
    r = _run(src)
    assert r["estimatedTimeS"] == pytest.approx(1.0, rel=1e-6)


def test_arc_quarter_circle_g2():
    # Start at (10, 0). Center at (0, 0) via I=-10 J=0. End at (0, 10).
    # Quarter circle CCW would be G3; G2 from (10,0) to (0,10) clockwise
    # actually goes the "long way" (3/4 turn). Use G3 for a quarter (CCW).
    src = """
    G90
    M82
    G1 F6000
    G1 X10 Y0 Z0.2 E0
    G3 X0 Y10 I-10 J0 E1
    """
    r = _run(src)
    # Print distance for the arc only = quarter circle of radius 10 = pi/2 * 10.
    expected = math.pi / 2 * 10
    # printDistance sums all extrusion moves; first move is travel only? No,
    # G1 X10 Y0 has E0 which equals current E (0), so de=0, not extrusion.
    assert r["printDistanceMm"] == pytest.approx(expected, rel=1e-6)


def test_arc_full_circle_g3():
    # From (10, 0) back to (10, 0) with center (0,0) via I=-10 J=0 = full
    # circle (sweep = 2*pi). Length = 2*pi*r = 2*pi*10.
    src = """
    G90
    M82
    G1 F6000
    G1 X10 Y0 Z0.2 E0
    G3 X10 Y0 I-10 J0 E1
    """
    r = _run(src)
    expected = 2 * math.pi * 10
    assert r["printDistanceMm"] == pytest.approx(expected, rel=1e-6)


def test_acceleration_short_segment():
    # Segment too short to reach feed-rate speed.
    # F=6000 -> v_target = 100 mm/s. Accel = 1500.
    # d_accel = v^2 / (2a) = 10000/3000 = 3.333 mm.
    # 2 * d_accel = 6.667 mm; dist=2 mm < 6.667 -> triangle profile.
    # t = 2 * sqrt(dist / a) = 2 * sqrt(2/1500) = ~0.0730s.
    src = """
    G90
    M82
    G1 F6000
    G1 X2 Y0 E1
    """
    r = analyze(src.splitlines(), accel_mm_s2=1500.0)
    expected = 2 * math.sqrt(2.0 / 1500.0)
    assert r["estimatedTimeS"] == pytest.approx(expected, rel=1e-6)


def test_acceleration_long_segment_trapezoid():
    # Long segment: v_target=100, a=1500, dist=100.
    # d_accel = 3.333; trapezoid time = 2*v/a + (dist - 2*d_accel)/v
    #         = 0.1333 + (100 - 6.667)/100 = 0.1333 + 0.9333 = 1.0667s.
    src = """
    G90
    M82
    G1 F6000
    G1 X100 Y0 E1
    """
    r = analyze(src.splitlines(), accel_mm_s2=1500.0)
    v = 100.0
    a = 1500.0
    expected = 2 * (v / a) + (100 - v * v / a) / v
    assert r["estimatedTimeS"] == pytest.approx(expected, rel=1e-6)


def test_toolpath_collected_when_requested():
    src = """
G90
M82
G1 X0 Y0 Z0.2
G1 X10 Y0 E1
G1 X20 Y0
G1 X20 Y10 E2
"""
    r = analyze(src.splitlines(), collect_toolpath=True, accel_mm_s2=None)
    tp = r["toolpath"]
    # 4 motion segments total: initial Z lift (travel), extrusion to X10,
    # travel to X20, extrusion to (X20,Y10). 6 floats per segment.
    assert tp["totalSegments"] == 4
    assert len(tp["extrusion"]) == 12  # 2 segments * 6
    assert len(tp["travel"]) == 12  # 2 segments * 6


def test_toolpath_absent_by_default():
    src = """
G90
M82
G1 X10 Y0 E1
"""
    r = analyze(src.splitlines(), accel_mm_s2=None)
    assert "toolpath" not in r


def test_toolpath_layer_offsets_from_comments():
    src = """
G90
M82
;LAYER:0
G1 X0 Y0 Z0.2
G1 X10 Y0 E1
;LAYER:1
G1 X10 Y10 Z0.4 E2
G1 X0 Y10 E3
"""
    r = analyze(src.splitlines(), collect_toolpath=True, accel_mm_s2=None)
    tp = r["toolpath"]
    # Layer 0: 1 travel (Z lift) + 1 extrusion. Layer 1: 2 extrusions.
    assert tp["layers"] == 2
    assert tp["extrusionLayerOffsets"] == [0, 1, 3]
    assert tp["travelLayerOffsets"] == [0, 1, 1]


def test_toolpath_layer_offsets_fallback_z():
    # No ;LAYER: comments: a new extrusion Z starts a new layer.
    src = """
G90
M82
G1 X0 Y0 Z0.2
G1 X10 Y0 E1
G1 X10 Y0 Z0.4
G1 X0 Y0 E2
"""
    r = analyze(src.splitlines(), collect_toolpath=True, accel_mm_s2=None)
    tp = r["toolpath"]
    assert tp["layers"] == 2
    assert tp["extrusionLayerOffsets"] == [0, 1, 2]
    # Initial Z lift and the Z hop between layers are both travel in layer 0
    # and layer 0 respectively (the hop happens before layer 1's extrusion).
    assert tp["travelLayerOffsets"] == [0, 2, 2]


def test_toolpath_layer_offsets_survive_decimation():
    # 40 layers x 5 extrusion segments, decimated to <= 20 segments.
    lines = ["G90", "M82"]
    for layer in range(40):
        lines.append(f";LAYER:{layer}")
        z = 0.2 * (layer + 1)
        lines.append(f"G1 X0 Y{layer} Z{z:.2f}")
        for i in range(5):
            lines.append(f"G1 X{(i + 1) * 10} Y{layer} E{layer * 5 + i + 1}")
    r = analyze(lines, collect_toolpath=True, accel_mm_s2=None,
                toolpath_max_segments=20)
    tp = r["toolpath"]
    ext = tp["extrusionLayerOffsets"]
    trav = tp["travelLayerOffsets"]
    assert tp["layers"] == 40
    assert len(ext) == 41 and len(trav) == 41
    # Offsets must be monotonic and account for every sampled segment.
    assert all(a <= b for a, b in zip(ext, ext[1:]))
    assert all(a <= b for a, b in zip(trav, trav[1:]))
    assert ext[-1] == len(tp["extrusion"]) // 6
    assert trav[-1] == len(tp["travel"]) // 6
    assert ext[-1] + trav[-1] == tp["sampledSegments"]


def test_avg_print_and_travel_speeds():
    # 100 mm extrusion at F3600 = 60 mm/s, 50 mm travel at F6000 = 100 mm/s.
    src = """
    G90
    M82
    G1 F3600
    G1 X100 Y0 E1
    G1 F6000
    G1 X150 Y0
    """
    r = _run(src)
    assert r["avgPrintSpeedMmS"] == pytest.approx(60.0, rel=1e-6)
    assert r["avgTravelSpeedMmS"] == pytest.approx(100.0, rel=1e-6)
